### PR TITLE
Add Hacktoberfest badge to the repository list

### PR DESCRIPTION
**Pull request by adeele**
Displays Hacktoberfest badge using badges/shield in the Repositories list
Zrzut ekranu 2022-10-19 o 09 13 46

### CODE REVIEW

**Comment by bgalek** [comment]
@adeele nice! resolve conflicts please :)

**Comment by bgalek** [comment]
also what do you think about aligning those badges to the right? :)

**Comment by adeele** [comment]
@bgalek we can always improve the design :) I updated the image - I aligned it right but made max width to avoid too big space. What do you think?

**Comment by bgalek** [comment]
i think it's cool! If you have better ideas feel free to update the UI :)

**Pull request merged**
